export const list = [
  {
    title: "Printful + Next.js Starter",
    img: '/demo1.svg',
    description: "This is a starter template built to be a 0 to production for $0 starting up cost",
    github: "https://github.com/lbsudo/printful-nextjs-starter",
    route: "https://printful-nextjs-starter.netlify.app/",
    react: true,
    next: true,
    ts: true,
    tw: true,
    fm: true,
    nu: true,
  },
  {
    title: "Covenant Society Clothing",
    img: '/demo2.svg',
    description: "An active online shop for my own personal brand using my Printful + `Next.js Starter` template",
    github: "https://github.com/lbsudo/covenant-society-shop",
    route: "https://covenant-society-shop.netlify.app/",
    react: true,
    next: true,
    ts: true,
    tw: true,
    fm: true,
    nu: true,
  },
  {
    title: "Cherese Monet Portfolio Site",
    img: '/demo3.svg',
    description: "",
    github: "https://github.com/lbsudo/cmonet",
    route: "https://cmonet-demo.netlify.app/",
    react: true,
    next: true,
    ts: true,
    tw: true,
    fm: true,
    nu: true,
  },
  {
    title: "Financial Services - Prototype",
    img: '/demo4.svg',
    description: "",
    github: "https://github.com/lbsudo/mojave-valley",
    route: "https://mojave-valley-prototype.netlify.app/",
    react: true,
    next: true,
    ts: true,
    tw: true,
    fm: true,
    nu: true,
  },
  // {
  //   title: "3D Tetris",
  //   img: '/propic.svg',
  //   description: "",
  //   github: "",
  //   route: "", react: true,
  //   next: true,
  //   ts: true,
  //   tw: true,
  //   fm: true,
  //   nu: true,
  // },
];
